Better UI for the Login
Kindev/fundraisee-web pull request #8
Opened 2018-07-07 13:18 UTC by fiennyangeln

## Summary

Provide Better UI for login

## Test plan

Use mobile and tablet resolution.

2018-07-07 14:34 UTC, endiliey requested changes
Can we make the UI to take the modal space as needed ?

<img width="951" alt="capture" src="https://user-images.githubusercontent.com/17883920/42411830-a24677a8-8235-11e8-81f9-d47a6609a031.PNG">

2018-07-07 16:45 UTC, fiennyangeln commented
@endiliey do you mean the default width? like the register page?

2018-07-07 17:26 UTC, endiliey commented
@fiennyangeln hmm i feel that there is lot of unused space. 

<img width="951" alt="capture" src="https://user-images.githubusercontent.com/17883920/42413200-f347f2a4-824d-11e8-9eba-26a79ad5781d.PNG">

WDYT?

2018-07-07 17:46 UTC, AlbertLucianto commented
I agree with @endiliey.

The differences I notice from the wireframe is that the wireframe uses

* wider text fields
* larger title
* larger vertical and bit smaller horizontal paddings

@fiennyangeln I think you have followed the wireframe quite well. But because the wireframe only presents squarer ratio, you might have taken measurements of the margins instead of the paddings. That's probably why it becomes much wider when the screen is.

2018-07-08 14:57 UTC, fiennyangeln commented
@AlbertLucianto i initially didnt take account padding and margin, i just use the default fullWidth options that material-ui have. Anyway, I updated it based on your input, pls review 😄

2018-07-08 15:15 UTC, endiliey commented on src/components/LoginModal/index.js
> +                An error has occured
oops.. 
```js
the {error] is intentional though, because we got error message from the api call
```

2018-07-08 15:16 UTC, AlbertLucianto commented on src/components/LoginModal/index.js
> +                An error has occured
Oh sorry I missed that, my bad.

2018-07-08 15:19 UTC, AlbertLucianto approved these changes
The rest looks good to me :thumbsup:

2018-07-08 15:49 UTC, endiliey approved these changes

2018-07-08 15:51 UTC, endiliey commented
LGTM for now

<img width="184" alt="nexus" src="https://user-images.githubusercontent.com/17883920/42421536-b60794fa-8309-11e8-8a2d-62f082f45216.PNG">

<img width="960" alt="tweak" src="https://user-images.githubusercontent.com/17883920/42421541-c1055626-8309-11e8-8556-e0ca0873b240.PNG">

2018-07-08 15:51 UTC, merged